### PR TITLE
Allow to set a custom host name

### PR DESCRIPTION
**Pull request by azachar**
Hello, 
my semantic release use ssh to log into GitLab (think of  ``'ssh://git@node01-domain.com:32123/owner/repo.git'``)  and more over this url is a bit different, that the url of GitLab website (think of ``http://domain.com:90'`` and not ``http:\\node01-domain.com:32123``). That is why I created this PR which allows you to use your custom host name for your changelog output.

Also, I created a test case and readme for my use case, so it is clear how to use this PR. 

Please let me know your feedback. 

I look forward to hearing from you soon!

Best regards,
Andrej

### CODE REVIEW

**Comment by pvdlg** [comment]
This is already supported via [`writerOpts` option](https://github.com/semantic-release/release-notes-generator#options):
```json
{
  "plugins": [
    ["semantic-release/release-notes-generator", {
      "preset": "angular",
      "writerOpts": {
        "host": "http://domain.com:90"
      }
    }]
  ]
}
```

**Comment by azachar** [comment]
Dear @pvdlg, 
I tried your suggestion, but with no success.  Could you please advice what I am doing wrong?

Thank you.

Best regards,
Andrej

**Comment by pvdlg** [comment]
Please provide:
- Your semantic-release config
- The exact version of `@semantic-release/release-notes-generator` you are using (please check the version inside your `node_modules` in case you have a lockfile)
- The changelog part that is problematic

**Comment by azachar** [comment]
Thank you for your quick response @pvdlg, I created a test case for it, have a look at https://github.com/semantic-release/release-notes-generator/compare/master...azachar:case128

Cheers,
Andrej

**Comment by pvdlg** [comment]
Oh sorry I gave you an erroneous config. The correct one is:
```
{
  "plugins": [
    ["semantic-release/release-notes-generator", {
      "preset": "angular",
       "host": "http://domain.com:90"
    }]
  ]
}
```
`host` is at the root of the config object and not in `writerOpts`

**Comment by azachar** [comment]
Thanks yes, this worked.

**Pull request closed without merging**
