### PR TITLE
fix: AWS CodeCommit compatibility

### PR DESCRIPTION
**Pull request by giacris82**
This PR fixes the #182 issue

### CODE REVIEW

**Review by vectorstain — APPROVED** [review]
Amazing feature! ✅🚀✨

**Review by AutomazioneTF — APPROVED** [review]

**Comment by giacris82** [comment]
@gr2m @UziTech @pvdlg
Cloud you please 🙏 review and close this PR ? It's almost urgent for us 😥!

**Review by Roberto-Itauros — COMMENTED** [review]
LGTM! 🚀 🔥

**Review by gr2m — APPROVED** [review]

**Comment by gr2m** [comment]
@giacris82 can you look into the failing test please?

**Comment by giacris82** [comment]
> @giacris82 can you look into the failing test please?

Checking

**Comment by giacris82** [comment]
Integration Tests fixed! Please @gr2m approve it again 🙏

**Pull request merged**
