### PR TITLE
Provision to override linkCompare via. writerOpts

### PR DESCRIPTION
**Pull request by nozelrosario**
Support for disable compare links generated due to overridden linkCompare value.

### CODE REVIEW

**Comment by pvdlg** [comment]
What is the problem you are trying to solve here?

**Comment by nozelrosario** [comment]
> What is the problem you are trying to solve here?
The problem is there is no provision to enable/disable the "linkCompare" ," linkReferences" properties of writerOpts during change-log generation. This fix will enable to propagate the user defined option values to the plugin.

**Comment by pvdlg** [comment]
> The problem is there is no provision to enable/disable the "linkCompare" ," linkReferences" properties of writerOpts during change-log generation. This fix will enable to propagate the user defined option values to the plugin.

Yes that's what the code is doing, I can see that. My question is why do you need to do that. What problem are you trying to solve. What's the point of setting those? What is the functional use case?

Also your change doesn't seems to do anything that can't already be done.

You can already pass `linkCompare` and `linkReferences` via `writerOpts` option:
```json
{
  "plugins": [
    ["semantic-release/release-notes-generator", {
      "preset": "angular",
      "writerOpts": {
        "linkCompare": false,
        "linkReferences": false
      }
    }]
  ]
}
```

Those are passed to the writer and and impact the final output.

**Comment by nozelrosario** [comment]
The functional use case is i need to disable the "git compare links" in the generated changelog. I need simple change-log with only git commit messages.  Also i want no hyper links to git references as well.

**Comment by pvdlg** [comment]
> The functional use case is i need to disable the "git compare links" in the generated changelog. I need simple change-log with only git commit messages. Also i want no hyper links to git references as well.

Then you'll get that with the configuration I provided above.

**Comment by nozelrosario** [comment]
Thanks for your prompt response. I expected the same, but it did not work for me. I found the value for linkCompare is defaulted to "currentTag && previousTag", So passing 'false' in the config does not take effect. Also the setting 'false' value for linkReferences  doesnot work as it doesnot get propagated to the changelog writer config. May be the issue lies at some other place, but all i need to achieve is changelog without hyperlinks. (the reason being the generated hyperlinks do not work with our internal git repo browser)

**Comment by pvdlg** [comment]
Indeed. I wasn't testing the right thing.
However I don't think those options should be part of `writerOpts` as `conventional-changelog/conventional-changelog` set them in the `context`.
I'll open a PR to add them as plugin options.

**Pull request closed without merging**
