### PR TITLE
fix: Fix configuration overwriting hierarchy

### LINKED ISSUE #62: referenceActions and issuePrefixes config are always overwritten by default values
Looking at the code 
```
const {issue, commit, referenceActions, issuePrefixes} =
    find(HOSTS_CONFIG, conf => conf.hostname === hostname) || HOSTS_CONFIG.default;
const parsedCommits = commits.map(rawCommit => ({
    ...rawCommit,
    ...conventionalCommitsParser(rawCommit.message, {...parserOpts, referenceActions, issuePrefixes}),
  }));
```

you can see how, no matter what you do, the `referenceActions` and `issuePrefixes` value of the configured parserOpts are always overwritten by values specified in release-notes-generator. this means that you cannot configure, for example, jira like references 

the cold should be 
```
const parsedCommits = commits.map(rawCommit => ({
    ...rawCommit,
    ...conventionalCommitsParser(rawCommit.message, {referenceActions, issuePrefixes, ...parserOpts}),
  }));
```

### PR DESCRIPTION
**Pull request by brokenmass**
Ensure that parserOpts/writerOpts options > preset/config options > host options

closes #62

### CODE REVIEW

**Comment by pvdlg** [comment]
Thanks! It's quite a lot of code changes that seems to go beyond fixing the issue reported.
It's no really a problem and the code looks good, but I'm going to need some time to review (most likely tonight or tomorrow).

**Comment by brokenmass** [comment]
no worries, take your time. 
I just condensed the configuration generation logic in a single location to ensure the hierarchy is correct.

**Comment by pvdlg** [comment]
Looking at you changes it seems there is a lot of refactoring that is not related to the issue #62.
The code looks ok, but I'm not sure that overall it makes things clearer. Some parts are an improvement but some other not so much.

I'd prefer to avoid this refactoring. The code is stable and running in production for several months now and I don't want to take the risk of introducing a bug while doing a refactoring that doesn't bring much value other than code style.

In addition I kept the dynamic loading of presets isolated in `lib/load-changelog-config.js` on purpose. We are planning to create a GitHub App and we can't dynamically load custom user modules in the app. So having that isolated in `lib/load-changelog-config.js` will make it easier to disable that feature only on the GitHub app.

Why not just the fix you mentioned in #62 ?
It would just change `...conventionalCommitsParser(rawCommit.message, {...parserOpts, referenceActions, issuePrefixes})` to `...conventionalCommitsParser(rawCommit.message, {referenceActions, issuePrefixes, ...parserOpts})`.

Then you can just modify [this test](https://github.com/semantic-release/release-notes-generator/blob/master/test/integration.test.js#L92-L125) to:
- add a custom `referenceActions` like `referenceActions: ['keyword']`
- change `'%%Fix%% First fix (fixes #123)'` into `'%%Fix%% First fix (keyword #123)'`
- change `'%%Update%% Second feature (fixes #456)'` to `'%%Update%% Second feature (keyword #456)'`
- Adapt the verification regex to match `keyword` instead of `fixes`

**Comment by brokenmass** [comment]
updated as requested

**Review by pvdlg — APPROVED** [review]

**Review by gr2m — APPROVED** [review]

**Pull request merged**
